name: Linha de Montagem Simples

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Exibir mensagem inicial
        run: echo "Iniciando processo..."

      - name: Simular montagem
        run: echo "Montando produto..."

      - name: Finalizar processo
        run: echo "Processo finalizado com sucesso!"
